In [30]:
import scipy.io as sci
import numpy as np
import glob

In [31]:
mat1 = sci.loadmat('StabilityofPCommonData/NumerosityTaskData/stabilitysub02day1_REAL_remux.mat')
mat2 = sci.loadmat('StabilityofPCommonData/NumerosityTaskData/stabilitysub02day2_REAL_remux.mat')

In [76]:
arr = np.array(mat1['trialData'])
right = np.empty((1,1), dtype = int)
for x in range(0, len(arr)):
    if ((arr[x][0] == arr[x][2]) and (arr[x][1] == arr[x][3])):
        right = np.append(right, 1)
    else:
        right = np.append(right, 0)
right = np.array(right[1:], ndmin = 2).T
arr = np.hstack((arr, right))
for i in range(0, len(arr)):
    print(arr[i])

[0 3 0 3 1]
[0 3 0 3 1]
[1 1 1 1 1]
[4 1 2 1 0]
[1 1 1 1 1]
[0 4 0 3 0]
[3 2 2 3 0]
[1 3 4 3 0]
[0 1 0 1 1]
[3 1 2 1 0]
[4 1 2 1 0]
[3 0 3 0 1]
[1 2 2 1 0]
[2 0 2 0 1]
[1 3 3 3 0]
[1 2 3 3 0]
[4 0 3 0 0]
[2 3 3 3 0]
[0 2 0 2 1]
[2 3 3 3 0]
[3 1 2 1 0]
[3 4 4 3 0]
[0 2 0 2 1]
[4 3 3 3 0]
[4 2 2 2 0]
[1 2 1 2 1]
[3 1 2 1 0]
[1 2 2 1 0]
[0 1 0 1 1]
[4 1 2 1 0]
[3 3 3 3 1]
[2 1 1 1 0]
[0 1 0 1 1]
[4 4 3 3 0]
[0 1 0 1 1]
[1 2 2 1 0]
[2 2 2 2 1]
[3 1 2 1 0]
[4 0 3 0 0]
[1 2 2 1 0]
[3 1 2 1 0]
[0 4 0 3 0]
[4 2 2 2 0]
[4 4 3 3 0]
[4 2 2 2 0]
[1 3 2 2 0]
[3 1 1 1 0]
[1 0 1 0 1]
[4 0 3 0 0]
[4 0 3 0 0]
[3 0 3 0 1]
[4 1 1 1 0]
[4 2 2 2 0]
[3 4 3 3 0]
[1 4 3 3 0]
[1 0 1 0 1]
[1 1 1 1 1]
[1 4 3 3 0]
[4 3 3 3 0]
[1 3 3 3 0]
[1 3 3 3 0]
[0 2 0 2 1]
[4 4 3 3 0]
[1 1 2 2 0]
[1 4 3 3 0]
[4 1 2 1 0]
[2 3 3 2 0]
[0 3 0 3 1]
[3 3 3 3 1]
[1 0 1 0 1]
[1 3 3 3 0]
[4 1 2 1 0]
[3 1 2 1 0]
[1 0 1 0 1]
[2 3 2 1 0]
[4 4 3 3 0]
[1 0 1 0 1]
[3 1 1 1 0]
[0 2 0 2 1]
[3 4 3 3 0]
[3 4 3 3 0]
[2 2 3 3 0]
[0 1 0 1 1]
[3 3

In [90]:
mat1 = sci.loadmat('StabilityofPCommonData/NumerosityTaskData/stabilitysub02day1_REAL_remux.mat')
arr = mat1['trialData']
right = np.empty((1,1), dtype = int)
for x in range(0, len(arr)):
    if ((arr[x][0] == arr[x][2]) and (arr[x][1] == arr[x][3])):
            right = np.append(right, 1)
    else:
            right = np.append(right, 0)
right = np.array(right[1:], ndmin = 2).T
arr = np.hstack((arr, right))
alldata = np.insert(arr, 0, 1, axis = 1)

print(alldata[0])

path = 'StabilityofPCommonData/NumerosityTaskData/*.mat'
files = glob.glob(path)
c = 2
for names in files[1:]:
    mat = sci.loadmat(names)
    # arr is a 2d array
    arr = np.array(mat['trialData'])
    right = np.empty((1,1), dtype = int)

    for x in range(0, len(arr)):
        if ((arr[x][0] == arr[x][2]) and (arr[x][1] == arr[x][3])):
            right = np.append(right, 1)
        else:
            right = np.append(right, 0)
    right = np.array(right[1:], ndmin = 2).T
    arr = np.hstack((arr, right))
    arr = np.insert(arr, 0, c, axis = 1)
    alldata = np.vstack((alldata, arr))
    c = c + 1
print(alldata)

[1 0 3 0 3 1]
[[  1   0   3   0   3   1]
 [  1   0   3   0   3   1]
 [  1   1   1   1   1   1]
 ..., 
 [100   3   4   3   3   0]
 [100   4   0   3   0   0]
 [100   1   4   3   3   0]]


In [116]:
arr1 = np.array([[1,2,3]])
arr2 = np.array([[4,5,6], [7,8,9]])
arr3 = np.vstack((arr1, arr2))
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])